import os
import argparse
from dotenv import load_dotenv
from ..common.db import init_db, close_db, get_db_session
from sqlalchemy import text


items = [
["TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_100","Yungang Zhou 周允刚","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_299","Shuang Wang 王爽","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_243","Bin Wang  王斌","TJ_049","Jane Cai  蔡佩珍","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","OSMO_059","Yap Han Yao 叶瀚耀","TJ_211","Jeff Liu 刘健"],
["WH_051","Lenis Wang 王领水","WH_043","Liang Xu 徐亮","NA","NA","WH_001","William Lian 连炜炜","NA","NA","WH_001","William Lian 连炜炜"],
["QD_262","Alec Geng 耿开诚","TJ_206","Shaozhi Liu  刘少志","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_277","Naihang Yu 于乃航","TJ_206","Shaozhi Liu  刘少志","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_296","Hanson Wang 王之瀚","TJ_206","Shaozhi Liu  刘少志","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_030","Bob Xu 许冬晨"],
["TJ_216","Yanhu Ma  马艳虎","QD_282","Derek Dong 董新辰","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["NT_311","Alex Ding 丁航","NT_223","Fuhai Liu 刘福海","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["DL_001","Yantao Shen 沈彦涛","OSMO_019","Chen Yushang 陈宇上","NA","NA","OSMO_019","Chen Yushang 陈宇上","OSMO_059","Yap Han Yao 叶瀚耀","NT_245","Xuelian Wang 王雪莲"],
["DL_004","Qingliang Kang 康清亮","DL_001","Yantao Shen 沈彦涛","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["TJ_390","Lynn Guo 郭孟玲","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_209","Dustin Liu 刘文博","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["WH_004","Wenjun Ding 丁文军","OSMO_006","Andy Huang 黄启炎","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_002","Chuah Choong Keat 蔡崇杰","WH_001","William Lian 连炜炜"],
["WH_011","Yilong Zheng 郑伊龙","WH_004","Wenjun Ding 丁文军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_013","Yiling Zhao 赵依玲","WH_004","Wenjun Ding 丁文军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_028","Zhanqiang Ning 宁战强","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_031","Ken Deng 邓懿波","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_045","Lim Shao Jun 林绍钧","WH_001","William Lian 连炜炜"],
["WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_045","Lim Shao Jun 林绍钧","WH_001","William Lian 连炜炜"],
["WH_038","Xiao Lv 吕潇","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_042","Xiaohui Yan 颜晓辉","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_053","Haoran Zheng  郑浩然","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_054","Jason Zhang 张振祥","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_056","Steven Jian  简众多","WH_004","Wenjun Ding 丁文军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_059","Wells Xiong 熊威","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_068"," Xin Jin 金鑫","WH_004","Wenjun Ding 丁文军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_061","Ciel Zou 邹承燕","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_062","Mono Cheng 程晓攸","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_063","Mao Li 李毛","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_070","Adams Zheng 郑庚涛","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_074","Jimmy Wang 王进","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_076","Wuqiang Lin 林武强","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_080","Nick Liu  柳念","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_082","Lu Hu 胡露","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_088","Hover Feng 冯浩","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_091","Jackson Pu 蒲潇","WH_032","Kuiwu Ding 丁魁吾","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_092","Meiyi Liu 刘美怡","WH_004","Wenjun Ding 丁文军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_094","Xuekai Zhou 周学凯","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["QD_220","Dragon Yang 杨龙","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_221","Ning Liu 刘宁","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_226","Chao Ding 丁超","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_231","Shuchao Cheng 成树超","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_232","Zhaoliang Sun 孙兆亮","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","NA","NA","OSMO_001","Sean He 何晓峰","TJ_030","Bob Xu 许冬晨","TJ_030","Bob Xu 许冬晨"],
["QD_249","Yanjiao Huo 霍艳娇","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_272","Lili Liu 刘利利","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_274","Jianxiang Li 李建祥","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_276","Fang Wang 王芳","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_281","Xiaotong Liu 刘晓彤","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_284","Ulla Liu 刘娟","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_288","Lisa Liu 刘庆晓","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_290","Nathan Li 李宁","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_293","Jacky Yuan 袁鹏程","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_294","David Huang 黄俊星","QD_242","Ke Zhang 张克","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["TJ_011","Xue Li  李雪","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_013","Xuesi Zhang  张学思","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_014","Chenxi Wang  王晨曦","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_015","Jinying Li 李金英","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_016","Fei Yin 尹飞","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","OSMO_002","Chuah Choong Keat 蔡崇杰","TJ_211","Jeff Liu 刘健"],
["TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_002","Chuah Choong Keat 蔡崇杰","TJ_211","Jeff Liu 刘健"],
["TJ_037","Jiajin Li  李佳津","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_045","Yueming Hu  胡月明","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_059","Yap Han Yao 叶瀚耀","TJ_211","Jeff Liu 刘健"],
["TJ_093","Yongshuai Men 门永帅","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_095","Bo Zhou 周博","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_207","Weiqing Li 李卫卿","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_222","Chao Hao 郝超","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_235","Xinxin Liu 刘欣欣","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_239","Junjie Lv 吕俊杰","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_241","Xiannian Wang 王先年","OSMO_042","Li Gengcai 李更才","NA","NA","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_242","Quan Zhao 赵佺","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","OSMO_059","Yap Han Yao 叶瀚耀","TJ_211","Jeff Liu 刘健"],
["TJ_244","Xueqian Ma 马雪倩","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_246","Qi Sun 孙琪","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_250","Bo Zhao 赵博","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_258","Yujia Dong 董雨佳","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_261","Yue Hu 胡越","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_262","Hanchun Guo 郭涵春","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_265","Chuang Zhao 赵闯","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_274","Hongchao Dou 窦洪超","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_276","Shuang Gao 高爽","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_277","Yujie Wang 王宇杰","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_278","Jinqiu Lu 卢晋秋","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_279","David Xu 许朝巍","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","OSMO_001","Sean He 何晓峰","TJ_211","Jeff Liu 刘健"],
["TJ_283","Chao Liang 梁超","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_284","Yonghui Li 李永会","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_285","Hongbo Wang 王洪波","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_286","Jinxuan Zhang 张晋瑄","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_292","Xin Zhang 张欣","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_295","Zhiwen Ning 宁治文","TJ_082","Annie Zhao 赵景岩","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_301","Jing Chen 陈静","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_304","Jingwen Sun 孙靖玟","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_311","Yuxi Shen 沈玉锡","TJ_017","Hongying Xia  夏红影","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_325","Wen Zhu 朱文","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_335","Tao Xie 谢涛","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_337","Xu Wang 王旭","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_373","Yaqing Rong 荣雅晴","TJ_083","Xiangyang Chen 陈向阳","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","NA","NA","OSMO_001","Sean He 何晓峰","NT_233","Alice Li 李新华","NT_245","Xuelian Wang 王雪莲"],
["NT_232","Lily Li 李彩君","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_234","Qingran Zhang 张清然","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_235","Zhuanxia Heng 衡转霞","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_248","Jian Wu 吴健","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_260","Parker Song 宋飞","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_271","Tanya Chen 陈梦颖","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_275","Ace Li 李翔","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_282","Chuanchuan Bai 白川川","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["SZ_105","Xiaoxia Luo 罗晓霞","NT_224","Ting Ye 叶婷","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","OSMO_002","Chuah Choong Keat 蔡崇杰","NT_245","Xuelian Wang 王雪莲"],
["WH_097","Conor Wu 伍逸飞","WH_033","Pengjun Liu 刘朋军","OSMO_006","Andy Huang 黄启炎","OSMO_001","Sean He 何晓峰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_022","Wen Yu 余文","OSMO_019","Chen Yushang 陈宇上","NA","NA","OSMO_019","Chen Yushang 陈宇上","OSMO_045","Lim Shao Jun 林绍钧","WH_001","William Lian 连炜炜"],
["WH_034","Yan Wang 王妍","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_040","Dandan Tian 田旦旦","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_049","Alex Fang 方少华","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_065","Dong Feng 冯东","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_077","Sara Li 李倩","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_079","YuanXiang Wang 王源翔","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_081","Sukky He  何雨彤 ","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_084","Liangxin Peng  彭靓歆","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_085","Mengyao Fu 付梦瑶","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_086","May Guo 郭青美","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_087","Lucky Liu 柳丹","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["WH_090","Arjen Feng 冯楚杰","WH_022","Wen Yu 余文","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","WH_001","William Lian 连炜炜"],
["QD_201","Zeliang Wang 王泽良","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_234","Zhipeng Chen 陈志鹏","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_240","Juncheng Chen 陈俊成","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_241","Jiangming An 安江明","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_260","Fang Wang 王芳","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_257","Qingyu Dong 董青宇","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_291","Jinbao Zhao 赵金宝","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_292","Sunny Xue 薛晶","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_297","Cici Yang 杨春丽","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_030","Bob Xu 许冬晨"],
["TJ_048","Xinyu Zhou  周新雨","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","TJ_279","David Xu 许朝巍","TJ_211","Jeff Liu 刘健"],
["TJ_062","Huichun Wang  王慧春","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","TJ_030","Bob Xu 许冬晨","TJ_211","Jeff Liu 刘健"],
["TJ_081","He Xu  徐赫","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_228","Zhenghao Liu  刘正浩","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_238","Dongbo Yang  杨东波","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","TJ_279","David Xu 许朝巍","TJ_211","Jeff Liu 刘健"],
["TJ_255","Shutong Zhang  张淑童","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_256","Yanntong Wang  王延桐","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_323","Wei Liu  刘薇","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_347","Rui Zhang 张睿","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_360","Changliang Liu  刘长亮","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_009","Jing Zhou 周静","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","TJ_030","Bob Xu 许冬晨","TJ_211","Jeff Liu 刘健"],
["TJ_031","Dong Zhang  张冬","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_067","Jing Xu 徐静","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_091","Yanfeng Li  李彦锋","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","TJ_279","David Xu 许朝巍","TJ_211","Jeff Liu 刘健"],
["TJ_099","Mengyao Zhang  张梦瑶","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_217","Meibo Li  李美伯","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_270","Changxin You  由长鑫","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_306","Xinyue Yuan  袁心悦","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_317","Jinwen Zhou 周晶雯","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","TJ_030","Bob Xu 许冬晨","TJ_211","Jeff Liu 刘健"],
["TJ_322","Shuo Yu  余硕","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","TJ_279","David Xu 许朝巍","TJ_211","Jeff Liu 刘健"],
["TJ_333","Lei Hou  侯蕾","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_348","Yongqiang Zhu  朱永强","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_361","Mingqiang Zhao 赵明强","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_080","Henry Ren 任志恒","OSMO_019","Chen Yushang 陈宇上","NA","NA","OSMO_019","Chen Yushang 陈宇上","TJ_030","Bob Xu 许冬晨","TJ_211","Jeff Liu 刘健"],
["TJ_218","Dean Tang 唐靓","OSMO_019","Chen Yushang 陈宇上","NA","NA","OSMO_019","Chen Yushang 陈宇上","OSMO_002","Chuah Choong Keat 蔡崇杰","TJ_211","Jeff Liu 刘健"],
["TJ_365","Tiesong Zhang 张铁松","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_366","Wei Du 杜威","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_376","Zefeng Liu  刘泽峰","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_378","Yunjie Ruan  阮运杰","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_380","Yu Song 宋宇","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_382","Hongxia Dong  董红霞","TJ_080","Henry Ren 任志恒","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_385","Ziwei Zhang  张子威","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","TJ_211","Jeff Liu 刘健"],
["NT_217","Wenyi Xue 薛文逸","NT_223","Fuhai Liu 刘福海","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_223","Fuhai Liu 刘福海","OSMO_019","Chen Yushang 陈宇上","NA","NA","OSMO_019","Chen Yushang 陈宇上","NT_245","Wang Xuelian 王雪莲","NT_245","Xuelian Wang 王雪莲"],
["NT_259","Mickey Mi 米奇","NT_223","Fuhai Liu 刘福海","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_263","Wenchai Guo 郭文钗","TJ_030","Bob Xu 许冬晨","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_269","Jessie Ye 叶涵乔","NT_223","Fuhai Liu 刘福海","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_273","Kui Zhu 祝奎","NT_223","Fuhai Liu 刘福海","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_290","Yun Huang 黄云","NT_223","Fuhai Liu 刘福海","NA","NA","OSMO_019","Chen Yushang 陈宇上","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["SZ_102","Jason Zhou 周锦华","TJ_218","Dean Tang 唐靓","NA","NA","OSMO_019","Chen Yushang 陈宇上","OSMO_043","Wang Licai 王立财","NT_245","Xuelian Wang 王雪莲"],
["WH_025","Mingxia Tian 田明霞","SZ_101","Bob Hao 郝海保","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_002","Chuah Choong Keat 蔡崇杰","WH_001","William Lian 连炜炜"],
["TJ_272","Shuang Song 宋爽","TJ_375","Zhen Li 李震","SZ_101","Bob Hao 郝海保","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_293","Haoran Yang 杨昊然","TJ_375","Zhen Li 李震","SZ_101","Bob Hao 郝海保","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_375","Zhen Li 李震","SZ_101","Bob Hao 郝海保","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_381","Min Zhang 张敏","TJ_375","Zhen Li 李震","SZ_101","Bob Hao 郝海保","OSMO_001","Sean He 何晓峰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_384","Boxian Liu 刘伯贤","TJ_375","Zhen Li 李震","SZ_101","Bob Hao 郝海保","OSMO_001","Sean He 何晓峰","OSMO_065","Yee Chun Teck 余俊德","TJ_211","Jeff Liu 刘健"],
["NT_262","David Xu 徐伟","SZ_101","Bob Hao 郝海保","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_043","Wang Licai 王立财","NT_245","Xuelian Wang 王雪莲"],
["NT_266","Heidi He 何欣星","SZ_101","Bob Hao 郝海保","NA","NA","OSMO_001","Sean He 何晓峰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_276","Ivey Zhang 张雷","SZ_101","Bob Hao 郝海保","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_065","Yee Chun Teck 余俊德","NT_245","Xuelian Wang 王雪莲"],
["SZ_101","Bob Hao 郝海保","OSMO_001","Sean He 何晓峰","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_065","Yee Chun Teck 余俊德","NT_245","Xuelian Wang 王雪莲"],
["SZ_103","Lee Mao 毛礼涛","SZ_101","Bob Hao 郝海保","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_065","Yee Chun Teck 余俊德","NT_245","Xuelian Wang 王雪莲"],
["NT_308","Jinbo Wang 王金波","SZ_101","Bob hao 郝海保","NA","NA","OSMO_001","Sean He 何晓峰","OSMO_065","Yee Chun Teck 余俊德","NT_245","Xuelian Wang 王雪莲"],
["WH_019","Anny  Zhang 张全双","WH_047","Shanshan Liu 刘珊珊","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_041","Freda Zhang 张芬芬","WH_047","Tan Chai Hui 陈家辉","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_045","Lim Shao Jun 林绍钧","WH_001","William Lian 连炜炜"],
["WH_047","Shanshan Liu 刘珊珊","NT_209","Bluse Chen 陈树涛","NA","NA","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_045","Lim Shao Jun 林绍钧","WH_001","William Lian 连炜炜"],
["WH_066","Maddie Chen 陈梦","WH_047","Shanshan Liu 刘珊珊","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_069","Tianpeng Wang 王天鹏","WH_047","Shanshan Liu 刘珊珊","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","WH_001","William Lian 连炜炜"],
["WH_073","Gary Mei 梅关羽","WH_047","Shanshan Liu 刘珊珊","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_065","Yee Chun Teck 余俊德","WH_001","William Lian 连炜炜"],
["QD_207","Jin Dang 党进","NT_209","Bluse Chen 陈树涛","NA","NA","OSMO_002","Chuah Choong Keat 蔡崇杰","TJ_030","Bob Xu 许冬晨","TJ_030","Bob Xu 许冬晨"],
["QD_229","Zhenlu Wang 王振鲁","QD_207","Jin Dang 党进","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_278","Xiaona Li 李晓娜","QD_207","Jin Dang 党进","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_030","Bob Xu 许冬晨"],
["NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_059","Yap Han Yao 叶瀚耀","TJ_211","Jeff Liu 刘健"],
["TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","NA","NA","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_085","Dingming Chai 柴鼎铭","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_092","Wenbiao Ma 马文彪","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","TJ_279","David Xu 许朝巍","TJ_211","Jeff Liu 刘健"],
["TJ_251","Zhihui An 安智慧","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_059","Yap Han Yao 叶瀚耀","TJ_211","Jeff Liu 刘健"],
["TJ_324","Chao Fu 付超","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_345","Saiya Wang 王赛娅","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_354","Panpan  Shao 邵盼盼","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_355","Lei  Cheng 程垒","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","TJ_279","David Xu 许朝巍","TJ_211","Jeff Liu 刘健"],
["TJ_357","Wenya Zou 邹温亚","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","Na","TJ_211","Jeff Liu 刘健"],
["TJ_362","Degang Bai 白德刚","TJ_073","Hongyan Guo 郭洪艳","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_065","Yee Chun Teck 余俊德","TJ_211","Jeff Liu 刘健"],
["TJ_367","Ning Gao  高宁","NT_209","Nyon Ken Yoong  阮健荣","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_369","Mei Zhang  张梅","NT_209","Ju Zhou 周炬","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_377","Haiyu  Zhang 张海宇","TJ_073","Nyon Ken Yoong  阮健荣","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","TJ_211","Jeff Liu 刘健"],
["NT_216","Ju Zhou 周炬","NT_209","Bluse Chen 陈树涛","NA","NA","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_065","Yee Chun Teck 余俊德","NT_245","Xuelian Wang 王雪莲"],
["NT_218","Xiaoyi Chen 陈孝意","NT_244","Wade Su 苏炜","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_244","Wade Su 苏炜","NT_209","Bluse Chen 陈树涛","NA","NA","OSMO_002","Chuah Choong Keat 蔡崇杰","OSMO_043","Wang Licai 王立财","NT_245","Xuelian Wang 王雪莲"],
["NT_274","Sun Sun 孙聪","NT_216","Ju Zhou 周炬","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_279","Guangqiang Wang 王广强","NT_216","Ju Zhou 周炬","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_285","Lixin Huang 黄立鑫","NT_244","Wade Su 苏炜","NT_209","Bluse Chen 陈树涛","OSMO_002","Chuah Choong Keat 蔡崇杰","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["WH_039","Kevin Zhou 周运凯","OSMO_003","Liu Huaxing 刘华兴","NA","NA","OSMO_003","Liu Huaxing 刘华兴","OSMO_004","Cui Yue 崔岳","WH_001","William Lian 连炜炜"],
["WH_050","Xuchong  Zhao 赵旭崇","WH_039","Kevin Zhou 周运凯","NA","NA","OSMO_003","Liu Huaxing 刘华兴","NA","NA","WH_001","William Lian 连炜炜"],
["WH_067","Yuntao Zhu 朱云涛","WH_039","Kevin Zhou 周运凯","NA","NA","OSMO_003","Liu Huaxing 刘华兴","NA","NA","WH_001","William Lian 连炜炜"],
["TJ_247","Guobin Cai 蔡国彬","TJ_330","Leiding Geng 耿镭钉","NA","NA","OSMO_003","Liu Huaxing 刘华兴","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_302","Liangjie Shi 史梁杰","TJ_330","Leiding Geng 耿镭钉","NA","NA","OSMO_003","Liu Huaxing 刘华兴","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_330","Leiding Geng 耿镭钉","OSMO_003","Liu Huaxing 刘华兴","NA","NA","OSMO_003","Liu Huaxing 刘华兴","OSEH_013","Nor Shah Izam bin Md Nor","TJ_211","Jeff Liu 刘健"],
["NT_267","Xinchen He 何欣晨","OSMO_003","Liu Huaxing 刘华兴","NA","NA","OSMO_003","Liu Huaxing 刘华兴","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["WH_006","Meng Wang 王萌","WH_009","Charline Zeng  曾婵娟","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","NA","NA","WH_001","William Lian 连炜炜"],
["WH_009","Charline Zeng  曾婵娟","TJ_210","Jay Zhao 赵建阳","NA","NA","TJ_211","Jeff Liu 刘健","TJ_210","Jay Zhao 赵建阳","WH_001","William Lian 连炜炜"],
["WH_012","Reed Ye  叶统","WH_009","Charline Zeng  曾婵娟","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","NA","NA","WH_001","William Lian 连炜炜"],
["WH_021","Chong Wei 魏冲","WH_023","Zhen Shen 沈振","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","WH_001","William Lian 连炜炜"],
["WH_023","Zhen Shen 沈振","TJ_049","Jane Cai  蔡佩珍","NA","NA","TJ_211","Jeff Liu 刘健","OSMO_045","Lim Shao Jun 林绍钧","WH_001","William Lian 连炜炜"],
["QD_202","Kerry Yang 杨世凯","WH_009","Charline Zeng  曾婵娟","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","NA","NA","WH_001","William Lian 连炜炜"],
["WH_036","Kevin Ye 叶昶","WH_023","Zhen Shen 沈振","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","WH_001","William Lian 连炜炜"],
["WH_037","Daryl Wu 吴佑平","WH_023","Zhen Shen 沈振","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","WH_001","William Lian 连炜炜"],
["WH_060","Hui Wang 王慧","WH_023","Zhen Shen 沈振","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","WH_001","William Lian 连炜炜"],
["WH_093","Guangqi Xu 徐光旗","WH_023","Zhen Shen 沈振","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","WH_001","William Lian 连炜炜"],
["QD_209","Pengcheng Ni 倪鹏程","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","TJ_210","Jay Zhao 赵建阳","TJ_030","Bob Xu 许冬晨"],
["QD_211","Fuqiang Liu 刘付强","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_212","Cissy Chen 陈茜","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_214","Jingyan Wang 王静妍","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_216","Qianqian Li 李倩倩","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_218","Chao Yang 杨超","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_219","Jenson Zhang 张建新","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健","TJ_210","Jay Zhao 赵建阳","TJ_030","Bob Xu 许冬晨"],
["QD_225","Sizhen Cai 蔡思振","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_227","Xuanxuan Dai 代旋旋","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_233","Owens Liu 刘光正","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_245","Linshuai Li 李林帅","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_246","Xingchen Jiang 姜晨星","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_247","Yuan Tian 田园","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_252","Bruce Lin 林国强","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_253","Guangcai Wu 吴广财","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_255","Jiachuan Li 李佳川","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_256","Sisi Li 李思斯","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_258","Yanjie Yang 杨艳杰","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_261","Hunter Liu 刘健","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_275","Jiayue Ji 姬嘉悦","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_287","Miya Xie 谢丽君","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["QD_298","Allen Liu 刘海涛","QD_219","Jenson Zhang 张建新","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","TJ_030","Bob Xu 许冬晨"],
["TJ_007","Xingguang Song 宋兴光","TJ_210","Jeff Liu 刘健","OSMO_004","Cui Yue 崔岳","TJ_211","Jeff Liu 刘健","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_024","Huanhuan Wang 王欢欢","TJ_243","Bin Wang 王斌","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_038","Jianwei Zhang  张建伟","TJ_049","Jane Cai  蔡佩珍","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_043","Yuhao Gu  谷宇豪","TJ_049","Jane Cai  蔡佩珍","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_046","Xiaolong Li  李小龙","TJ_049","Jane Cai  蔡佩珍","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_049","Jane Cai  蔡佩珍","TJ_211","Jeff Liu 刘健","OSMO_004","Cui Yue 崔岳","TJ_211","Jeff Liu 刘健","OSMO_004","Cui Yue 崔岳","TJ_211","Jeff Liu 刘健"],
["TJ_069","Weihua Hu  胡卫华","TJ_049","Jane Cai  蔡佩珍","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_088","Yang Liu  刘扬","TJ_049","Jane Cai  蔡佩珍","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","OSMO_043","Wang Licai 王立财","TJ_211","Jeff Liu 刘健"],
["TJ_204","Dongbin Hou  侯栋宾","TJ_210","Jay Zhao 赵建阳","OSMO_055","Yang Wei 杨威","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","OSMO_004","Cui Yue 崔岳","TJ_211","Jeff Liu 刘健","OSMO_004","Cui Yue 崔岳","TJ_211","Jeff Liu 刘健"],
["TJ_215","Chunyi Zhu  朱春义","TJ_243","Bin Wang 王斌","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_219","Xingyun Cui  崔兴运","TJ_364","Eric Li 李学华","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_225","Chuang Wang   王闯","TJ_210","Jay Zhao 赵建阳","OSMO_055","Yang Wei 杨威","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_227","Yu Wang  王雨","TJ_379","Devin Liu 刘荣行","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_237","Li Liu  刘丽","TJ_379","Devin Liu 刘荣行","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_245","Hailong Liang  梁海龙","TJ_379","Devin Liu 刘荣行","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_249","Shengzhi Liu  刘胜智","TJ_210","Jay Zhao 赵建阳","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_253","Chunpeng Li  李淳鹏","TJ_210","Jay Zhao 赵建阳","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_263","Shuping Ruan  阮淑萍","TJ_243","Bin Wang 王斌","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_266","Lin Li  李琳","TJ_243","Bin Wang 王斌","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_267","Qiang Zhou  周强","TJ_007","Xingguang Song 宋兴光","OSMO_004","Cui Yue 崔岳","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_268","Wenxuan Zhao  赵文轩","TJ_364","Eric Li 李学华","TJ_210","Jay Zhao 赵建阳","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_294","Ao Liu 刘傲","TJ_007","Xingguang Song 宋兴光","OSMO_004","Cui Yue 崔岳","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_297","Rui Wang 王瑞","TJ_210","Jay Zhao 赵建阳","OSMO_055","Yang Wei 杨威","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_313","Bowei Li  李博巍","TJ_210","Jay Zhao 赵建阳","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_314","Qi Li  李琦","TJ_007","Xingguang Song 宋兴光","OSMO_004","Cui Yue 崔岳","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_328","Zhanquan Fan 范占泉","TJ_243","Bin Wang 王斌","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_329","Zeyao Guo 郭泽耀","TJ_210","Jay Zhao 赵建阳","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_334","Shupeng Shan 单书鹏","TJ_210","Jay Zhao 赵建阳","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_341","Rui Ren 任睿","TJ_243","Bin Wang 王斌","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_359","Runguang Yu 于润光","TJ_049","Jane Cai  蔡佩珍","OSMO_058","Chris Luan 栾林昌","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_364","Xuehua Li 李学华","TJ_210","Jay Zhao 赵建阳","OSMO_055","Yang Wei 杨威","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_379","Ronghang Liu 刘荣行","TJ_210","Jay Zhao 赵建阳","OSMO_055","Yang Wei 杨威","TJ_211","Jeff Liu 刘健","NA","NA","TJ_211","Jeff Liu 刘健"],
["NT_221","Limo Zhu 朱利模","TJ_049","Jane Cai  蔡佩珍","NA","NA","TJ_211","Jeff Liu 刘健","TJ_030","Bob Xu 许冬晨","NT_245","Xuelian Wang 王雪莲"],
["NT_252","Victor Thet Htwe Aung ","OSMO_044","Kong Kim Fong 江金峰","NA","NA","TJ_211","Jeff Liu 刘健","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_256","Dan Zhou 周丹","NT_221","Limo Zhu 朱利模","TJ_049","Jane Cai 蔡佩珍","TJ_211","Jeff Liu 刘健","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_307","Tian Jin 金天","OSMO_058","Chris Luan 栾林昌","OSMO_044","Kong Kim Fong 江金峰","TJ_211","Jeff Liu 刘健","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["WH_005","Betty Zhou 周雅茹","WH_043","Liang Xu 徐亮","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","WH_001","William Lian 连炜炜"],
["WH_029","Tengfei Zhou 周腾飞","WH_043","Liang Xu 徐亮","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","WH_001","William Lian 连炜炜"],
["WH_043","Liang Xu 徐亮","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","OSMO_045","Lim Shao Jun 林绍钧","WH_001","William Lian 连炜炜"],
["WH_072","Eric Xiong 熊云飞","WH_043","Liang Xu 徐亮","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","WH_001","William Lian 连炜炜"],
["WH_089","Maggie Jie 揭胜男","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","NA","NA","WH_001","William Lian 连炜炜"],
["QD_282","Derek Dong 董新辰","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","TJ_279","David Xu 许朝巍","TJ_030","Bob Xu 许冬晨"],
["TJ_006","Jiantang Wei  魏建堂","WH_001","William Lian 连炜炜","NA","NA","WH_001","William Lian 连炜炜","OSMO_065","Yee Chun Teck 余俊德","TJ_211","Jeff Liu 刘健"],
["TJ_040","Yameng Chen  陈亚萌","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_052","Ruiqi Li  李睿琪","TJ_275","Huipeng Yan  闫慧朋","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_098","Shanshan Yu  于闪闪","TJ_206","Shaozhi Liu  刘少志","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_206","Shaozhi Liu  刘少志","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","OSMO_059","Yap Han Yao 叶瀚耀","TJ_211","Jeff Liu 刘健"],
["TJ_240","Jiajun Sun  孙佳俊","TJ_275","Huipeng Yan  闫慧朋","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_275","Huipeng Yan  闫慧朋","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","NT_233","Alice Li 李新华","TJ_211","Jeff Liu 刘健"],
["TJ_287","Ao Zou 邹奥","TJ_206","Shaozhi Liu  刘少志","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_303","Pengpeng Guo 郭鹏鹏","TJ_206","Shaozhi Liu  刘少志","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_318","Ruipeng Feng 冯睿鹏","TJ_206","Shaozhi Liu  刘少志","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_320","Huifang Li 李慧芳","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["TJ_327","Shishuo  Liu 刘释烁","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","OSMO_059","Yap Han Yao 叶瀚耀","TJ_211","Jeff Liu 刘健"],
["TJ_353","Shuo Li 李硕","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","NA","NA","TJ_211","Jeff Liu 刘健"],
["NT_264","Fisher Xu 徐舒阳","TJ_275","Huipeng Yan  闫慧朋","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_272","Adele Yang 杨晶淳","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_286","Jeff Huang 黄东伟","WH_001","William Lian 连炜炜","NA","NA","WH_001","William Lian 连炜炜","OSMO_013","Meng Xianbo 孟宪波","NT_245","Xuelian Wang 王雪莲"],
["NT_289","Flynn Gao 高翔","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["NT_292","Kitty Huang 黄宇晴","TJ_275","Huipeng Yan  闫慧朋","TJ_006","Jiantang 魏建堂","WH_001","William Lian 连炜炜","NA","NA","NT_245","Xuelian Wang 王雪莲"],
["DL_003","Jacky Wang 王天宇","TJ_006","Jiantang Wei  魏建堂","NA","NA","WH_001","William Lian 连炜炜","NT_245","Wang Xuelian 王雪莲","NT_245","Xuelian Wang 王雪莲"],
["TJ_371","Wei Qin 秦伟","NT_245","Xuelian Wang 王雪莲","NA","NA","NT_245","Xuelian Wang 王雪莲","NT_245","Wang Xuelian 王雪莲","NT_245","Xuelian Wang 王雪莲"]
]

if __name__ == '__main__':
    # 先加载配置再初始化组件
    parser = argparse.ArgumentParser()
    parser.add_argument('--env', type=str, default='testing')
    args, _ = parser.parse_known_args()
    print(args)

    current_script_path = os.path.abspath(__file__)
    project_dir = os.path.dirname(current_script_path)
    env_file = f'{project_dir}/../config/.env.{args.env}'
    print(env_file)
    if os.path.exists(env_file):
        load_dotenv(env_file, override=True)

    init_db()

    session = get_db_session()

    index = 1
    sql = "select name from saint_whale_auth.users where username = :code and status != 'DELETED'"
    name_map = {}
    for item in items:
        index += 1
        for i in range(1,7):
            j = i*2
            code = item[j-2]
            name = item[j-1]
            if code == "NA" or name == "NA":
                continue
            result = session.execute(text(sql), {"code": code, "name": name}).fetchone()
            db_cn_name = result[0].split()[-1]
            excel_cn_name = name.split()[-1]
            if db_cn_name != excel_cn_name:
                if result[0] not in name_map:
                    name_map[result[0]] = [[index, code, name, result[0]]]
                else:
                    name_map[result[0]].append([index, code, name, result[0]])
                #print(index, code, name, result[0])
    for key in name_map:
        for item in name_map[key]:
            print(item)
