package com.ose.vo;

public enum BpmTaskDefKey {

    ////* 此代码跟工作流设定相关联，禁止删除跟修改 *////
    // GateWay
    EXCLUSIVE_GATEWAY_RESULT("RESULT", "排他网关判断条件"),
    EXCLUSIVE_GATEWAY_RESULT_REJECT("REJECT", "拒绝"), // 驳回,拒绝
    EXCLUSIVE_GATEWAY_RESULT_ACCEPT("ACCEPT", "接受"), //接受,通过
    EXCLUSIVE_GATEWAY_RESULT_PENDING("PENDING", "待定"), //待定,通过
    EXCLUSIVE_GATEWAY_RESULT_NEED("NEED", "机具参与出库"),
    EXCLUSIVE_GATEWAY_RESULT_NONEED("NONEED", "不需机具参与"),
    EXCLUSIVE_GATEWAY_RESULT_COORDINATE("COORDINATE", "有协调员"),
    EXCLUSIVE_GATEWAY_RESULT_NO_COORDINATE("NO_COORDINATE", "无协调员"),
    EXCLUSIVE_GATEWAY_RESULT_COMMENT("COMMENT", "有意见"),
    EXCLUSIVE_GATEWAY_RESULT_NO_COMMENT("NO_COMMENT", "无意见"),
    EXCLUSIVE_GATEWAY_RESULT_NOT_NEED_EXPAND_WELD("NOT_NEED_EXPAND_WELD", "不需要扩口"),
    EXCLUSIVE_GATEWAY_RESULT_NEED_EXPAND_WELD("NEED_EXPAND_WELD", "扩口"),
    EXCLUSIVE_GATEWAY_RESULT_NEED_DESIGN_CHANGE("NEED_DESIGN_CHANGE", "增加设计变更"),
    EXCLUSIVE_GATEWAY_RESULT_NDT_TODO("NDT_TODO", "100%检验 或 扩口 或 返修"),
    EXCLUSIVE_GATEWAY_RESULT_NDT_APPLY("NDT_APPLY", "NDT申请"),
    EXCLUSIVE_GATEWAY_RESULT_NDT("NDT", "做NDT"),
    EXCLUSIVE_GATEWAY_RESULT_NO_NDT("NO_NDT", "不做NDT"),
    EXCLUSIVE_GATEWAY_RESULT_SKIP_NDT("SKIP_NDT", "跳过NDT"),
    EXCLUSIVE_GATEWAY_RESULT_REPAIR("REPAIR", "返修"),
    EXCLUSIVE_GATEWAY_RESULT_RE_NDT("RE_NDT", "报告不合格，重新NDT"),
    EXCLUSIVE_GATEWAY_RESULT_COMPLETE("COMPLETE", "整改完成"),
    EXCLUSIVE_GATEWAY_RESULT_PMI_TODO("PMI_TODO", "100%检验 或 返修"),
    EXCLUSIVE_GATEWAY_RESULT_PMI_APPLY("PMI_APPLY", "PMI申请"),
    EXCLUSIVE_GATEWAY_RESULT_PMI("PMI", "做PMI"),
    EXCLUSIVE_GATEWAY_RESULT_NO_PMI("NO_PMI", "不做PMI"),
    EXCLUSIVE_GATEWAY_RESULT_ACCEPT_SIGN("ACCEPT_SIGN", "有意见"),
    EXCLUSIVE_GATEWAY_RESULT_REPORT_NG("REPORT_NG", "报告错误"),
    EXCLUSIVE_GATEWAY_RESULT_REPORT_OK("REPORT_OK", "报告正确"),
    USERTASK_CO_SIGN("usertask-CO-SIGN", "用户节点-会签"),
    CO_SIGN("CO_SIGN", "会签"),

    // userTask
    USERTASK_FOREMAN_DISPATCH("usertask-FOREMAN-DISPATCH", "用户任务-班长任务分配", BpmTaskType.FOREMAN_DISPATCH),
    USERTASK_LEADER_DISPATCH("usertask-LEADER-DISPATCH", "用户任务-组长任务分配", BpmTaskType.FOREMAN_DISPATCH),
    USERTASK_NDT_SUPERVISOR_DISPATCH("usertask-NDT-SUPERVISOR-DISPATCH", "用户任务-NDT主管任务分配", BpmTaskType.NDT_SELECT),
    USERTASK_DRAWING_SIGN("usertask-DRAWING-SIGN", "用户任务-图纸会签", BpmTaskType.DRAWING_COSIGN),
    USERTASK_COSIGN("usertask-USER-DRAWING-COSIGN", "图纸会签", BpmTaskType.DRAWING_COSIGN),
    USERTASK_DRAWING_ISSUED("usertask-DRAWING-ISSUED", "用户任务-图纸签发", BpmTaskType.DRAWING_ISSUE),
    USERTASK_DRAWING_REGISTER("usertask-DRAWING-REGISTER", "用户任务-登记文档信息", BpmTaskType.DRAWING_REGISTER),
    UT_CONFIRM_DRAWING_APPROVED("UT-CONFIRM_DRAWING_APPROVED", "确认图纸过审", BpmTaskType.DRAWING_APPROVE),
    USERTASK_DRAWING_DESIGN("usertask-USER-DRAWING-DESIGN", "用户任务-设计人员绘制图纸", BpmTaskType.DRAWING_DESIGN),
    USERTASK_DRAWING_MODIFY("usertask-USER-DRAWING-MODIFY", "用户任务-设计人员修改图纸", BpmTaskType.DRAWING_MODIFY),
    USERTASK_DRAWING_MODIFY_SHORTCUT("usertask-USER-DRAWING-MODIFY_SHORTCUT", "用户任务-设计人员修改图纸", BpmTaskType.DRAWING_MODIFY),
    USERTASK_DRAWING_REVISE("usertask-USER-DRAWING-REVISE", "用户任务-设计人员修改图纸", BpmTaskType.DRAWING_MODIFY),
    USERTASK_DRAWING_CHECK("usertask-USER-DRAWING-CHECK", "用户任务-校对", BpmTaskType.DRAWING_CHECK),
    USERTASK_QC_CHECK("usertask-USER-QC-CHECK", "用户任务-校对", BpmTaskType.DRAWING_QC_CHECK),
    USERTASK_DRAWING_REVIEW("usertask-USER-DRAWING-REVIEW", "用户任务-审核", BpmTaskType.DRAWING_REVIEW),
    USERTASK_DRAWING_DISPATCH("usertask-DRAWING-DISPATCH", "用户任务-图纸派发并回传签字传送单", BpmTaskType.DRAWING_DISPATCH),
    USERTASK_DRAWING_APPROVE("usertask-USER-DRAWING-APPROVE", "用户任务-批准", BpmTaskType.DRAWING_APPROVE),
    USERTASK_GOE_APPROVE("usertask-GOE-APPROVE", "GOE审核", BpmTaskType.DRAWING_SEND_EMAIL),
    USERTASK_UPLOAD_REPORT("usertask-UPLOAD-REPORT", "用户任务-上传报告", BpmTaskType.EX_INSP_UPLOAD_REPORT),
    USERTASK_ENTER_EX_COMMENT("usertask-ENTER-EX-COMMENT", "用户任务-输入外检意见", BpmTaskType.INPUT_EX_COMMENT),
    USERTASK_ENTER_QC_COMMENT("usertask-ENTER-QC-COMMENT", "用户任务-输入内检意见", BpmTaskType.INPUT_IN_COMMENT),
    USERTASK_PIPE_PIECE_CUTTING_EXECUTE("usertask-PIPE-PIECE-CUTTING-EXECUTE", "用户任务-下料执行", BpmTaskType.CONSTRUCT_PIPING_CUTTING),
    USERTASK_QRCODE_PASTE("usertask-QRCODE-PASTE", "用户任务-下料执行", BpmTaskType.CONSTRUCT_PIPING_CUTTING),
    USERTASK_WELD_EXECUTE("usertask-WELD_EXECUTE", "用户任务-焊接执行", BpmTaskType.WELD_EXECUTE),
    USERTASK_NDT_EXECUTE("usertask-NDT-EXECUTE", "用户任务-工人探伤", BpmTaskType.NDT_EXECUTE),
    USERTASK_OWNER_EXTERNAL_INSPECTION("UT-UPLOAD_EXTERNAL_INSPECTION_REPORT", "用户任务-业主外检", BpmTaskType.EX_INSP_UPLOAD_REPORT),
    USERTASK_THIRD_EXTERNAL_INSPECTION("UT-UPLOAD_EXTERNAL_INSPECTION_REPORT", "用户任务-第三方外检", BpmTaskType.EX_INSP_UPLOAD_REPORT),
    USERTASK_OTHER_EXTERNAL_INSPECTION("UT-UPLOAD_EXTERNAL_INSPECTION_REPORT", "用户任务-其他外检", BpmTaskType.EX_INSP_UPLOAD_REPORT),
    USERTASK_OWNER_EXTERNAL_INSPECTION_APPLY("UT-APPLY_EXTERNAL_INSPECTION", "用户任务-业主外检申请", BpmTaskType.EX_INSP_APPLY),
    USERTASK_THIRD_EXTERNAL_INSPECTION_APPLY("UT-APPLY_EXTERNAL_INSPECTION", "用户任务-第三方外检申请", BpmTaskType.EX_INSP_APPLY),
    USERTASK_OTHER_EXTERNAL_INSPECTION_APPLY("UT-APPLY_EXTERNAL_INSPECTION", "用户任务-其他外检申请", BpmTaskType.EX_INSP_APPLY),
    USERTASK_SEND_EXTERNAL_INSPECTION_EMAIL("UT-SEND_EXTERNAL_INSPECTION_EMAIL", "用户任务-发送外检申请邮件", BpmTaskType.EX_INSP_APPLY_MAIL),
    USERTASK_THIRD_EXTERNAL_INSPECTION_COORDINATE("UT-SEND_EXTERNAL_INSPECTION_EMAIL", "用户任务-第三方外检安排", BpmTaskType.EX_INSP_APPLY_MAIL),
    USERTASK_OTHER_EXTERNAL_INSPECTION_COORDINATE("UT-SEND_EXTERNAL_INSPECTION_EMAIL", "用户任务-其他外检安排", BpmTaskType.EX_INSP_APPLY_MAIL),
    USERTASK_NDT_CHECK("usertask-NDT-CHECK", "用户任务-系统NDT检查", BpmTaskType.NDT_INIT_CHECK),
    USERTASK_NDT_APPLY_CONFIRM("usertask-NDT-APPLY-CONFIRM", "用户任务-主管NDT申请确认", BpmTaskType.NDT_EXECUTE),
    USERTASK_NDT_REPORT_INPUT("usertask-NDT-REPORT-INPUT", "用户任务-填写探伤报告", BpmTaskType.GENERATE_NDT_REPORT),
    USERTASK_NDT_REPORT_UPLOAD("usertask-NDT-REPORT-UPLOAD", "用户任务-QC上传报告", BpmTaskType.NDT_UPLOAD_REPORT),
    USERTASK_NDT_REPAIR_CONFIRM("usertask-NDT-REPAIR-CONFIRM", "用户任务-返修结果确认", BpmTaskType.NDT_ANALYZE_NG_RESULT),
    USERTASK_NDT_EXPAND_CONFIRM("usertask-NDT-EXPAND-CONFIRM", "用户任务-扩口确认", BpmTaskType.NDT_ANALYZE_NG_RESULT),
    USERTASK_DESIGN_CHANGE_CONFIRM("usertask-DESIGN-CHANGE-CONFIRM", "用户任务-扩口确认", BpmTaskType.NDT_ANALYZE_NG_RESULT),
    USERTASK_CREATE_CHANGE_TASK("usertask-CREATE-CHANGE-TASK", "用户任务-设计工程师创建变更任务", BpmTaskType.SUPERVISOR_CHANGE_CONFIRM),
    USERTASK_CREATE_CHANGE_DUE_TO_DRAWING("usertask-CREATE-CHANGE-DUE-TO-DRAWING", "用户任务-设计工程师创建变更任务 由于涉及原因"),
    USERTASK_CREATE_CHANGE_DUE_TO_CONSTRUCT("usertask-CREATE-CHANGE-DUE-TO-CONSTRUCT", "用户任务-设计工程师创建变更任务 由于建造"),
    USERTASK_DESIGNER_ACCEPT_TASK("usertask-DESIGNER-ACCEPT-TASK", "用户任务-设计人员确认接受任务"),
    USERTASK_DESIGNER_UPLOAD_CHANGE_LIST("usertask-DESIGNER-UPLOAD-CHANGE-LIST", "用户任务-设计工程师上传设计变更审核单"),
    USERTASK_SUPERVISOR_CHANGE_CONFIRM("usertask-SUPERVISOR-CHANGE-CONFIRM", "用户任务-管道主管确定是否创建建造变更"),
    USERTASK_PMI_CHECK("usertask-PMI-CHECK", "用户任务-系统PMI检查", BpmTaskType.PMI_INIT_CHECK),
    USERTASK_QC_SUPERVISOR_CONFIRM("usertask-QC-SUPERVISOR-CONFIRM", "用户任务-QC主管确认", BpmTaskType.QC_EX_CONFIRM),
    USERTASK_PMI_SUPERVISOR_CONFIRM("usertask-PMI-SUPERVISOR-CONFIRM", "用户任务-PMI主管确认", BpmTaskType.PMI_CONFIRM_REPORT),
    USERTASK_PUNCHLIST_CHARGER_ASIGN("usertask-PUNCHLIST-CHARGER-ASIGN", "用户任务-QC责任人指派意见整改人"),
    USERTASK_QC_UPLOAD_REPORT("usertask-QC-REPORT-UPLOAD", "用户任务-QC上传报告", BpmTaskType.EX_INSP_UPLOAD_REPORT),
    USERTASK_UPLOAD_NG_REPORT("usertask-REPORT-NG-UPLOAD", "用户任务-上传NG报告", BpmTaskType.EX_INSP_UPLOAD_REPORT),
    USERTASK_QC_UPLOAD_NG_REPORT("usertask-QC-REPORT-NG-UPLOAD", "用户任务-QC上传不合格报告", BpmTaskType.EX_INSP_UPLOAD_REPORT),
    USERTASK_QC_UPLOAD_NDT_NG_REPORT("usertask-QC-REPORT-NDT_NG-UPLOAD", "用户任务-QC上传NDT不合格报告", BpmTaskType.NDT_UPLOAD_REPORT),
    USERTASK_QC_UPLOAD_PMI_NG_REPORT("usertask-QC-REPORT-PMI_NG-UPLOAD", "用户任务-QC上传PMI不合格报告", BpmTaskType.PMI_UPLOAD_REPORT),
    USERTASK_PMI_REPORT_UPLOAD("usertask-PMI-REPORT-UPLOAD", "用户任务-QC上传报告", BpmTaskType.PMI_UPLOAD_REPORT),
    USERTASK_NDT_SUPERVISOR_CONFIRM("usertask-NDT-SUPERVISOR-CONFIRM", "用户任务-NDT主管结果判定", BpmTaskType.NDT_CONFIRM_REPORT),
    USERTASK_PMI_APPLY_CONFIRM("usertask-PMI-APPLY-CONFIRM", "用户任务-QC主管抽取焊口", BpmTaskType.PMI_SELECT),
    USERTASK_INPUT_NDT_TEST_REPORT("usertask-ENGINEER-INPUT-NDT-REPORT", "用户任务-NDT工程师生成合格探伤报告", BpmTaskType.GENERATE_NDT_REPORT),
    USERTASK_INPUT_NDT_TEST_REPORT_NG("usertask-ENGINEER-INPUT-NDT-REPORT-NG", "用户任务- NDT工程师生成不合格探伤报告", BpmTaskType.GENERATE_NG_NDT_REPORT),
    USERTASK_SUPERVISOR_CHECK_NG("usertask-SUPERVISOR-CHECK-NG", "主管不合格复核", BpmTaskType.SUPERVISOR_CONFIRM),
    USERTASK_NDT_SUPERVISOR_CHECK_NDT_EXEXUTE("usertask-NDT-SUPERVISOR-CHECK-NDT-EXECUTE", "NDT主管审核", BpmTaskType.NDT_CONFIRM_REPORT),
    //    USERTASK_NDT_SUPERVISOR_CONFIRM("usertask-NDT-SUPERVISOR-CONFIRM", "NDT主管线下审核合格报告"),
    USERTASK_NDT_SUPERVISOR_CONFIRM_NG("usertask-NDT-SUPERVISOR-CONFIRM-NG", "NDT主管线下审核不合格报告", BpmTaskType.NDT_CONFIRM_REPORT),
    USERTASK_NDT_ENGINEER_EXECUTE("usertask-NDT-ENGINEER-EXECUTE", "NDT工程师现场探伤", BpmTaskType.NDT_EXECUTE),
    USERTASK_PUNCHLIST_DELEGATE_OTHER("usertask-PUNCHLIST-DELEGATE-OTHER", "委托其他责任人"),
    //    USERTASK_PUNCHLIST_CHARGER_ASIGN("usertask-PUNCHLIST-CHARGER-ASIGN", "QC跟踪人指派意见责任人"),
    USERTASK_UPLOAD_EDIT_REVIEW_LIST("usertask-UPLOAD_EDIT_REVIEW_LIST", "上传可编辑版最终变更评审单", BpmTaskType.DRAWING_UPLOAD_VOR),
    USERTASK_DESIGN_DOCUMENT_CONTROL_EXECUTE("usertask-DESIGN_DOCUMENT_CONTROL_EXECUTE", "上传签字版变更评审单", BpmTaskType.DRAWING_UPLOAD_CHANGE_ORDER),
    USERTASK_SUPERVISOR_UPLOAD_CHANGE_ORDER("usertask-SUPERVISOR-UPLOAD-CHANGE-ORDER", "管道主管上传签字版作业变更指令单"),
    USERTASK_SUPERVISOR_CONFIRM_RELEASE_LIST("usertask-SUPERVISOR-CONFIRM-RELEASE-LIST", "生产主管确认放行单&二维码打印", BpmTaskType.SUPERVISOR_CONFIRM),
    USERTASK_INSPECTION_RESULT_CONFIRM("usertask-INSPECTION-RESULT-CONFIRM", "内检结果判定", BpmTaskType.QC_IN_CONFIRM),
    USERTASK_FITUP_EXECUTE("usertask-FITUP_EXECUTE", "组对执行", BpmTaskType.FITUP_EXECUTE),
    USERTASK_USER_DRAWING_DESIGN("usertask-USER-DRAWING-DESIGN", "图纸设计", BpmTaskType.DRAWING_DESIGN),
    USERTASK_REDMARK_DESIGN("usertask-REDMARK-DESIGN", "图纸REDMARK设计", BpmTaskType.REDMARK_DESIGN),
    USERTASK_REDMARK_CHECK("usertask-REDMARK-CHECK", "图纸REDMARK校对", BpmTaskType.REDMARK_CHECK),
    USERTASK_REDMARK_RECEIPT("usertask-REDMARK-RECEIPT", "图纸REDMARK接收", BpmTaskType.REDMARK_RECEIPT),
    USERTASK_REDMARK_MODIFY("usertask-REDMARK-MODIFY", "图纸REDMARK修改", BpmTaskType.REDMARK_DESIGN),
    USERTASK_CUTTING_AND_PRINT_QRCODE("UT-CUTTING_AND_PRINT_QRCODE", "材料下料和扫码追溯", BpmTaskType.CONSTRUCTION),

    // material
    USERTASK_MATERIAL_RECEIVE_STOCK_TAKE("UT-TAKE_STOCK", "用户任务-材料入库-库管物资盘点"),
    USERTASK_MATERIAL_RECEIVE_QC_INTERNAL_INSPECTION("usertask-MATERIAL-RECEIVE-QC-INTERNAL-INSPECTION", "用户任务-材料入库-QC内检"),
    USERTASK_MATERIAL_RECEIVE_INTERNAL_INSPECTION_PROBLEMS("UT-RECORD_INTERNAL_QUALITY_ISSUES", "用户任务-材料入库-内检质量问题清单"),
    USERTASK_MATERIAL_RECEIVE_EXTERNAL_INSPECTION_PROBLEMS("UT-RECORD_EXTERNAL_QUALITY_ISSUES", "用户任务-材料入库-外检质量问题清单"),
    USERTASK_MATERIAL_RECEIVE_MATERIAL_RECEIVE("UT-WRITEBACK_MATERIAL_INFO", "用户任务-材料入库-入库"),
    UT_WRITEBACK_RECEIVED_MATERIAL_INFO("UT-WRITEBACK_RECEIVED_MATERIAL_INFO", "用户任务-结构材料入库-入库"),

    USERTASK_MATERIAL_ISSUE_CREATE_PREPARE("usertask-MATERIAL-ISSUE-CREATE-PREPARE", "用户任务-材料出库-用料计划单生成"),
    USERTASK_MATERIAL_SURPLUS_RECEIPTS_CREATE("usertask-MATERIAL-SURPLUS-RECEIPTS-CREATE", "用户任务-余料套料-用料计划单生成"),
    USERTASK_MATERIAL_ISSUE_PREPARE_APPROVAL("usertask-MATERIAL-ISSUE-PREPARE-APPROVAL", "用户任务-材料出库-技术部接收"),
    USERTASK_MATERIAL_MATCH_SOLUTION("usertask-MATERIAL-MATCH-SOLUTION", "用户任务-材料出库-套料上传套料清单"),
    USERTASK_MATERIAL_ISSUE_CONTROLLER_RECEIVE("usertask-MATERIAL-ISSUE-CONTROLLER-RECEIVE", "用户任务-材料出库-材料控制工程师接收"),
    USERTASK_MATERIAL_ISSUE_CONTROLLER_RECEIVE_ISO_COMP("usertask-MATERIAL-ISSUE-CONTROLLER-RECEIVE-ISO-COMP", "用户任务-材料出库-材料控制工程师接收(外场管附件)"),
    USERTASK_MATERIAL_ISSUE_CONTROLLER_RECEIVE_SP_COMP("usertask-MATERIAL-ISSUE-CONTROLLER-RECEIVE-SP-COMP", "用户任务-材料出库-材料控制工程师接收(内场管附件)"),
    CREATE_SPM_REQUISITION("UT-CREATE_SPM_REQUISITION", "用户任务-材料出库-领料单生成"),
    USERTASK_MATERIAL_ISSUE_CREATE_REQUISITION("usertask-MATERIAL-ISSUE-CREATE-REQUISITION", "用户任务-材料出库-领料单生成"),
    USERTASK_MATERIAL_ISSUE_RECEIVE("usertask-MATERIAL-ISSUE-RECEIVE", "用户任务-材料出库-仓库接收"),
    UT_RECHECK_REQUISITION("UT-RECHECK_REQUISITION", "结构套料-材料出库-仓库接收"),
    UT_COUNT_ISSUE_LIST("UT-COUNT_ISSUE_LIST", "结构套料-材料出库-盘点出库"),
    USERTASK_MATERIAL_ISSUE_MATERIAL_ISSUE("usertask-MATERIAL-ISSUE-MATERIAL-ISSUE", "用户任务-材料出库-盘点出库"),
    UT_CONFIRM_WRITEBACK_VALIDITY("UT-CONFIRM_WRITEBACK_VALIDITY", "结构套料出库-确认反写SPM成功"),
    UT_CONFIRM_NESTING_PLAN_AND_CUTTING("UT-CONFIRM_NESTING_PLAN_AND_CUTTING", "确认套料方案，直接进入切割工序"),
    UT_WRITEBACK_ISSUED_MATERIAL_INFO("UT-WRITEBACK_ISSUED_MATERIAL_INFO", "结构材料出库-SPM数据库反写"),
    USERTASK_ASSIGN_DELIVERY_ADDRESS("usertask-ASSIGN-DELIVERY-ADDRESS", "用户任务-材料出库-配送至指定地点"),
    USERTASK_MATERIAL_ISSUE_ISSUE_RECEIPT_CONFIRM("usertask-MATERIAL-ISSUE-ISSUE-RECEIPT-CONFIRM", "用户任务-材料出库-材料接收"),
    USERTASK_CONSTRUCTION_SUPERVISOR_CONFIRM("usertask-CONSTRUCTION-SUPERVISOR-CONFIRM", "用户任务-材料出库-生产主管确认"),
    USERTASK_MATERIAL_ISSUE_NESTING("usertask-MATERIAL-ISSUE-NESTING", "用户任务-材料出库-套料"),
    USERTASK_MATERIAL_SURPLUS_RECEIPTS_NESTING("usertask-MATERIAL-SURPLUS-RECEIPTS-NESTING", "用户任务-余料-套料"),

    USERTASK_MATERIAL_TRANSFER_RECEIVE_CONFIRM("usertask-MATERIAL-TRANSFER-RECEIVE-CONFIRM", "用户任务-材料配送-签收材料并填写数量"),
    USERTASK_MATERIAL_TRANSFER_SUPERVISOR_CONFIRM("usertask-MATERIAL-TRANSFER-SUPERVISOR-CONFIRM", "用户任务-材料配送-主管确认"),

    USERTASK_MATERIAL_RETURN_CREATE_RETURN_TASK("usertask-MATERIAL-RETURN-CREATE-RETURN-TASK", "用户任务-材料退库-创建材料退库单"),
    USERTASK_MATERIAL_RETURN_RETURN_SCANNING("usertask-MATERIAL-RETURN-RETURN-SCANNING", "用户任务-材料退库-退库材料扫描"),
    USERTASK_MATERIAL_RETURN_RETURN_SUBMIT("usertask-MATERIAL-RETURN-RETURN-SUBMIT", "用户任务-材料退库-退库单提交"),
    USERTASK_MATERIAL_RETURN_RETURN_CHECK("usertask-MATERIAL-RETURN-RETURN-CHECK", "用户任务-材料退库-退库单签核"),
    USERTASK_MATERIAL_RETURN_WAREHOUSE_CONFIRMATION("usertask-MATERIAL-RETURN-WAREHOUSE-CONFIRMATION", "用户任务-材料退库-仓库确认"),
    USERTASK_MATERIAL_RETURN_RETURN_MATERIAL_INSPECTION("usertask-MATERIAL-RETURN-RETURN-MATERIAL-INSPECTION", "用户任务-材料退库-退库物资报验"),
    USERTASK_MATERIAL_RETURN_QUALITY_SUPERVISOR_ACCEPT("usertask-MATERIAL-RETURN-QUALITY-SUPERVISOR-ACCEPT", "用户任务-材料退库-质量主管接受并指派质量人员"),
    USERTASK_MATERIAL_RETURN_ACCEPTANCE("usertask-MATERIAL-RETURN-ACCEPTANCE", "用户任务-材料退库-质量检验人员验收并剔除不合格产品"),
    USERTASK_MATERIAL_RETURN_WAREHOUSE_RECEIVE_CONFIRM("usertask-MATERIAL-RETURN-WAREHOUSE-RECEIVE-CONFIRM", "用户任务-材料退库-仓库确认材料是否可以退入仓库"),
    USERTASK_MATERIAL_RETURN_WAREHOUSE_RECEIVE("usertask-MATERIAL-RETURN-WAREHOUSE-RECEIVE", "用户任务-材料退库-材料退入仓库，并写入SPM"),
    USERTASK_MATERIAL_RETURN_RECEIVE_WRITE_IN_RIGHT("usertask-MATERIAL-RECEIVE-WRITE-IN-RIGHT", "用户任务-材料退库-确定反写数据正确"),
    UT_CONFIRM_MATERIAL_RECEIPT("UT_CONFIRM_MATERIAL_RECEIPT", "结构套料-材料接收"),
    UT_CONFIRM_NESTING_PLAN("UT-CONFIRM_NESTING_PLAN", "结构套料材料确认套料方案"),
    UT_CREATE_SPM_REQUISITION("UT-CREATE_SPM_REQUISITION", "结构套料材料生成SPM领料单"),

    // 下料
    UT_CHECK_CUTTING_TASK_LIST("UT-CHECK_CUTTING_TASK_LIST", "主管复核下料单", BpmTaskType.SUPERVISOR_CONFIRM),
    UT_CUT_PIPE_PIECE("UT-CUT_PIPE_PIECE", "切割下料段", BpmTaskType.CONSTRUCT_PIPING_CUTTING),
    UT_PASTE_QRCODE("UT-PASTE_QRCODE", "打印并粘帖下料段二维码", BpmTaskType.CONSTRUCT_PIPING_CUTTING),
    UT_SUPERVISOR_SOLVE_MISTAKES("UT-SUPERVISOR_SOLVE_MISTAKES", "主管处理下料错误", BpmTaskType.SUPERVISOR_CONFIRM),




    USERTASK_RECEIVE_CHECK_EXECUTE("usertask-RECEIVE-CHECK-EXECUTE", "接收执行动作", BpmTaskType.HANDOVER_EXECUTE),
    USERTASK_SPOOL_RELEASE_EXECUTE("usertask-SPOOL-RELEASE-EXECUTE", "单管放行执行动作", BpmTaskType.RELEASE_EXECUTE),

    USERTASK_PMI_EXECUTE("usertask-PMI_EXECUTE", "PMI执行", BpmTaskType.PMI_EXECUTE),
    USERTASK_PWHT_EXECUTE("usertask-PWHT_EXECUTE", "PWHT执行", BpmTaskType.PWHT_EXECUTE),

    UT_CONSTRUCTION_MANAGER_AUDIT("usertask-CONSTRUCTION-MANAGER-AUDIT","建造经理审核RT探伤作业", BpmTaskType.CON_MANAGER_CONFIRM),
    UT_CONSTRUCTION_WELD_CHANGE_CONFIRM("usertask-CONSTRUCTION-WELD-CHANGE-CONFIRM","确认焊口返工，并引起建造变更"),
    UT_CONSTRUCTION_WELD_REPAIR_CONFIRM("usertask-CONSTRUCTION-WELD-REPAIR-CONFIRM","确认焊口返修"),
    UT_GENERATE_PMI_TEST_REPORT("usertask-GENERATE-PMI-TEST-REPORT","生成PMI报告", BpmTaskType.GEN_REPORT),
    UT_GENERATE_PWHT_TEST_REPORT("usertask-GENERATE-PWHT-TEST-REPORT","生成焊后热处理报告", BpmTaskType.GEN_REPORT),
    UT_MATERIAL_ISSUE_RECHECK("usertask-MATERIAL-ISSUE-RECHECK","下料组确认领料单"),
    UT_NDT_SUB_WORKFLOW_STARTUP("usertask-NDT-SUB-WORKFLOW-STARTUP","系统启动NDT子流程"),
    UT_NDT_SUPERVISOR_CHECK_NDT_WELD("usertask-NDT-SUPERVISOR-CHECK-NDT-WELD","NDT主管现场审核RT、UT、MT、PT焊口", BpmTaskType.NDT_CONFIRM_REPORT),
    UT_NDT_SUPERVISOR_DISPATCH_RT("usertask-NDT-SUPERVISOR-DISPATCH-RT","NDT主管分配RT、UT、MT、PT任务", BpmTaskType.SUPERVISOR_DISPATCH),
    UT_PMI_FIELD_TEST("usertask-PMI-FIELD-TEST","现场PMI测试并判定结果", BpmTaskType.PMI_EXECUTE),
    UT_PMI_REPAIR_CONFIRM("usertask-PMI-REPAIR-CONFIRM","系统分析返修焊口信息", BpmTaskType.PMI_ANALYZE_NG_RESULT),
    UT_QC_ACCEPT_INSPECTION("usertask-QC-ACCEPT-INSPECTION","QC接收内检申请", BpmTaskType.QC_IN_CONFIRM),
    UT_QC_SUPERVISOR_CHECK("usertask-QC-SUPERVISOR-CHECK","QC主管现场审核PMI焊口", BpmTaskType.PMI_CONFIRM_REPORT),
    UT_QC_SUPERVISOR_DISPATCH("usertask-QC-SUPERVISOR-DISPATCH","QC主管分配任务", BpmTaskType.SUPERVISOR_DISPATCH),
    UT_RECEIVE_CHECK_BATCH_CONFIRM("usertask-RECEIVE-CHECK-BATCH-CONFIRM","主管接收，批量确认", BpmTaskType.SUPERVISOR_CONFIRM),
    UT_RECEIVE_CHECK_CONFIRM("usertask-RECEIVE-CHECK-CONFIRM","主管接收", BpmTaskType.SUPERVISOR_CONFIRM),
    UT_RT_INSPECT_SAFTY_APPLY("usertask-RT-INSPECT-SAFTY-APPLY","无损探伤检测中安全申请"),
    UT_SAFTY_SUPERVISOR_CONFIRM("usertask-SAFTY-SUPERVISOR-CONFIRM","安全主管确认", BpmTaskType.HSE_CONFIRM),
    UT_SPOOL_RELEASE_EXECUTE("usertask-SPOOL_RELEASE_EXECUTE","放行执行", BpmTaskType.RELEASE_EXECUTE),
    UT_START_NDT_INSPECTION("usertask-START-NDT-INSPECTION","开始无损探伤检测", BpmTaskType.NDT_EXECUTE),
    UT_SUPERVISOR_ASSIGN_MATERIAL_RECEIVER("usertask-SUPERVISOR-ASSIGN-MATERIAL-RECEIVER","生产主管指派领料人", BpmTaskType.SUPERVISOR_DISPATCH),
    UT_SUPERVISOR_CONFIRM_LIST("usertask-SUPERVISOR-CONFIRM-LIST","主管确认清单", BpmTaskType.SUPERVISOR_CONFIRM),
    UT_SUPERVISOR_IN_INSPECTION_APPLY("usertask-SUPERVISOR-IN-INSPECTION-APPLY","主管申请内检", BpmTaskType.SUPERVISOR_APPLY),
    usertask_SUPERVISOR_PREPARE_NDT_WELD("usertask-SUPERVISOR-PREPARE-NDT-WELD","生产主管准备NDT焊口"),
    usertask_SUPERVISOR_REPAIR_CONFIRM("usertask-SUPERVISOR-REPAIR-CONFIRM","确认焊口返修"),
    UT_TRANSPORT_BATCH_PREPARE("usertask-TRANSPORT-BATCH-PREPARE","配送理料（批量确认）", BpmTaskType.HANDOVER_EXECUTE),
    UT_TRANSPORT_PREPARE("usertask-TRANSPORT-PREPARE","配送理料与扫码", BpmTaskType.HANDOVER_EXECUTE),
    UT_USER_DRAWING_AUDIT("usertask-USER-DRAWING-AUDIT","审核", BpmTaskType.DRAWING_REVIEW),
    UT_UT_CONFIRM_CANCEL_WRITEBACK("UT_CONFIRM_CANCEL_WRITEBACK","再次确认不反写入库"),
    UT_ACCEPT_INSPECTION_APPLICATION("UT-ACCEPT_INSPECTION_APPLICATION","QC接受开箱检验", BpmTaskType.QC_EX_CONFIRM),
    UT_ASSIGN_MACHINERY_WORKER("UT-ASSIGN_MACHINERY_WORKER","指派机具人员"),
    UT_CHECK_EXTERNAL_INSPECTION_REPORT("UT-CHECK_EXTERNAL_INSPECTION_REPORT","处理外检报告"),
    UT_CONFIRM_MACHINERY_ARRIVAL("UT-CONFIRM_MACHINERY_ARRIVAL","确认机具到位"),
    UT_COORDINATE_EXTERNAL_INSPECTION_APPLICATION("UT-COORDINATE_EXTERNAL_INSPECTION_APPLICATION","协调外检申请", BpmTaskType.EX_INSP_APPLY_MAIL),
    UT_CUTTING_AND_PRINT_QRCODE("UT-CUTTING_AND_PRINT_QRCODE","材料下料并打印二维码", BpmTaskType.CONSTRUCT_PIPING_CUTTING),
    UT_DELIVER_ON_SITE("UT-DELIVER_ON_SITE","配送至指定地点"),
    UT_DESIGN_CHANGE_CONFIRM("UT-DESIGN-CHANGE-CONFIRM","确认焊口返工，并引起建造变更"),
    UT_FOREMAN_ASSIGN_TASKS("UT-FOREMAN_ASSIGN_TASKS","班组长分配任务", BpmTaskType.FOREMAN_DISPATCH),
    UT_INPUT_MISTAKE_INFO("UT-INPUT_MISTAKE_INFO","填写错误说明"),
    UT_INTERNAL_INSPECTION("UT-INTERNAL_INSPECTION","QC内检", BpmTaskType.QC_IN_CONFIRM),
    UT_MATERIAL_REQUISITION_CHECK("UT-MATERIAL-REQUISITION-CHECK","下料组确认领料单"),
    UT_MODIFY_NESTING_PLAN("UT-MODIFY_NESTING_PLAN","修改套料方案"),
    UT_NDT_EXECUTE("UT-NDT_EXECUTE","无损探伤检测中", BpmTaskType.NDT_EXECUTE),
    UT_NDT_APPLY_CONFIRM("UT-NDT-APPLY-CONFIRM","NDT主管抽取焊口", BpmTaskType.NDT_SELECT),
    UT_NDT_CHECK("UT-NDT-CHECK","系统NDT检查", BpmTaskType.NDT_INIT_CHECK),
    UT_NDT_REPAIR_CONFIRM("UT-NDT-REPAIR-CONFIRM","系统分析返修焊口信息", BpmTaskType.NDT_ANALYZE_NG_RESULT),
    UT_NDT_SUPERVISOR_CHECK_NDT_EXECUTE("UT-NDT-SUPERVISOR-CHECK-NDT-EXECUTE","NDT主管审核", BpmTaskType.NDT_CONFIRM_REPORT),
    UT_PICKOUT_EXTERNAL_QUALITY_ISSUES("UT-PICKOUT_EXTERNAL_QUALITY_ISSUES","库管剔除外检质量问题产品"),
    UT_PICKOUT_INTERNAL_QUALITY_ISSUES("UT-PICKOUT_INTERNAL_QUALITY_ISSUES","库管剔除内检问题产品"),
    UT_RECHECK_CLASS_B_REPORT("UT-RECHECK_CLASS_B_REPORT","再处理B类报告", BpmTaskType.EX_INSP_REHANDLE_REPORT),
    UT_SPECIFY_EXTERNAL_INSPECTION_ROUTE("UT-SPECIFY_EXTERNAL_INSPECTION_ROUTE","指定外检方式"),
    UT_SPECIFY_WRITEBACK_ROUTE("UT-SPECIFY_WRITEBACK_ROUTE","判定是否反写入库"),
    UT_SUPERVISOR_ASSIGN_TASKS("UT-SUPERVISOR_ASSIGN_TASKS","主管派工", BpmTaskType.SUPERVISOR_DISPATCH),
    UT_SUPERVISOR_PREPARE_NDT_WELD("UT-SUPERVISOR-PREPARE-NDT-WELD","生产主管准备NDT焊口"),
    UT_SUPERVISOR_REPAIR_CONFIRM("UT-SUPERVISOR-REPAIR-CONFIRM","确认焊口返修", BpmTaskType.NDT_CONFIRM_REPORT),
    UT_UPLOAD_BOM("UT-UPLOAD_BOM","上传套料图、发料BOM"),
    UT_UPLOAD_RENEWED_REPORT("UT-UPLOAD_RENEWED_REPORT","回传重签报告"),


    START_EVENT("startEvent", "开始事件"),
    END_EVENT("endEvent", "结束事件"),
    USERTASK("userTask", "用户任务"),
    EXCLUSIVE_GATEWAY("exclusiveGateway", "排他网关"),
    PARALLEL_GATEWAY("parallelGateway", "并行网关"),
    INCLUSIVE_GATEWAY("inclusiveGateway", "包含网关");

    private String type;
    private String displayName;
    private BpmTaskType taskType;

    BpmTaskDefKey(String type, String displayName) {
        this.type = type;
        this.displayName = displayName;
    }

    BpmTaskDefKey(String type, String displayName, BpmTaskType taskType) {
        this.type = type;
        this.displayName = displayName;
        this.taskType = taskType;
    }


    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getTaskType() {
        return taskType == null ? null : taskType.name();
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }


    public static BpmTaskDefKey valueof(String taskDefKey){

        try {
            return BpmTaskDefKey.valueOf(taskDefKey);
        } catch (Exception e) {
            return null;
        }

    }

}
