USE `saint_whale_tasks`;

CREATE OR REPLACE VIEW `wbs_entries_plain` AS
USE `saint_whale_tasks`;
CREATE
	OR REPLACE VIEW `wbs_entries_plain` AS SELECT
	`we`.`id` AS `id`,
	`we`.`created_at` AS `created_at`,
	`we`.`last_modified_at` AS `last_modified_at`,
	`we`.`status` AS `status`,
	`we`.`created_by` AS `created_by`,
	`we`.`deleted` AS `deleted`,
	`we`.`deleted_at` AS `deleted_at`,
	`we`.`deleted_by` AS `deleted_by`,
	`we`.`last_modified_by` AS `last_modified_by`,
	`we`.`version` AS `version`,
	`we`.`active` AS `active`,
	`we`.`company_id` AS `company_id`,
	`we`.`depth` AS `depth`,
	`we`.`duration` AS `duration`,
	`we`.`duration_unit` AS `duration_unit`,
	`we`.`finish_at` AS `finish_at`,
	`we`.`guid` AS `guid`,
	`we`.`name` AS `name`,
	`we`.`no` AS `no`,
	`we`.`org_id` AS `org_id`,
	`we`.`parent_id` AS `parent_id`,
	`wb`.`path` AS `path`,
	`ws`.`progress` AS `progress`,
	`we`.`project_id` AS `project_id`,
	`ws`.`project_id` AS `s_project_id`,
	`ws`.`started_at` AS `start_at`,
	`we`.`type` AS `type`,
	`wb`.`wbs` AS `wbs`,
	`we`.`entity_id` AS `entity_id`,
	`we`.`process` AS `process`,
	`we`.`sector` AS `sector`,
	`we`.`stage` AS `stage`,
	`we`.`entity_sub_type` AS `entity_sub_type`,
	`we`.`entity_type` AS `entity_type`,
	`we`.`module_type` AS `module_type`,
	`we`.`project_node_id` AS `project_node_id`,
	`we`.`proportion` AS `proportion`,
	`ws`.`team_id` AS `team_id`,
	`we`.`hierarchy_node_id` AS `hierarchy_node_id`,
	`we`.`parent_hierarchy_node_id` AS `parent_hierarchy_node_id`,
	`we`.`random_no` AS `random_no`,
	`ws`.`team_path` AS `team_path`,
	`ws`.`finished` AS `finished`,
	`ws`.`finished_score` AS `finished_score`,
	`ws`.`total_score` AS `total_score`,
	`ws`.`started_at` AS `started_at`,
	`ws`.`started_by` AS `started_by`,
	`we`.`module_hierarchy_node_id` AS `module_hierarchy_node_id`,
	`we`.`process_id` AS `process_id`,
	`ws`.`process_instance_id` AS `process_instance_id`,
	`wb`.`remarks` AS `remarks`,
	`ws`.`work_site_id` AS `work_site_id`,
	`ws`.`work_site_name` AS `work_site_name`,
	`ws`.`work_site_address` AS `work_site_address`,
	`ws`.`finished_at` AS `finished_at`,
	`ws`.`running_status` AS `running_status`,
	`we`.`start_before_hours` AS `start_before_hours`,
	`ws`.`actual_man_hours` AS `actual_man_hours`,
	`we`.`estimated_man_hours` AS `estimated_man_hours`,
	`ws`.`actual_duration` AS `actual_duration`,
	`we`.`start_unix_time` AS `start_unix_time`,
	`ws`.`task_package_id` AS `task_package_id`,
	`we`.`layer_package` AS `layer_package`,
	`we`.`discipline` AS `discipline`,
	`ws`.`work_load` AS `work_load`,
	`we`.`dwg_sht_no` AS `dwg_sht_no`,
	`ws`.`team_name` AS `team_name`,
	`we`.`sector` AS `module_no`,
	0 AS `bom_match_percent`,
	'' AS `spm_ln_id`,
	0 AS `issue_status`,
	'' AS `hn_path`,
	`we`.`sort` AS `sort`
FROM
	(
		( `wbs_entry` `we` JOIN `wbs_entry_state` `ws` ON ( ( `we`.`id` = `ws`.`wbs_entry_id` ) ) )
	JOIN `wbs_entry_blob` `wb` ON ( ( `we`.`id` = `wb`.`wbs_entry_id` ) )
	);

